/** 旧 vicons 组件名 → iconify 字符串 */
const ICON_MAP: Record<string, string> = {
  Image: 'ant-design:file-image-outlined',
  FontColorsOutlined: 'ant-design:font-colors-outlined',
  FontSizeOutlined: 'ant-design:font-size-outlined',
  ItalicOutlined: 'ant-design:italic-outlined',
  Box: 'carbon:box',
  IdcardOutlined: 'ant-design:idcard-outlined',
  DataBaseAlt: 'carbon:data-base-alt',
  OpenPanelRight: 'carbon:open-panel-right',
  RowCollapse: 'carbon:row-collapse',
  Chat: 'carbon:chat',
  Notebook: 'carbon:notebook',
  CloudAlerting: 'carbon:cloud-alerting',
  Slisor: 'carbon:scissors',
  DataTable: 'carbon:data-table',
  UserMultiple: 'carbon:user-multiple',
  TouchInteraction: 'carbon:touch-interaction',
  Link: 'carbon:link',
  Erase: 'carbon:erase',
  ListNumbered: 'carbon:list-numbered',
  StorageRequest: 'carbon:storage-request',
  TextIndentMore: 'carbon:text-indent-more',
  JoinLeft: 'carbon:join-left',
  Timer: 'carbon:timer',
  EventSchedule: 'carbon:event-schedule',
  RadioButtonChecked: 'carbon:radio-button-checked',
  CheckboxChecked: 'carbon:checkbox-checked',
  DecisionTree: 'carbon:decision-tree',
  CloudUpload: 'carbon:cloud-upload',
  NotAvailable: 'carbon:not-available',
  StudyTransfer: 'carbon:study',
  DataFormat: 'carbon:data-format',
  HorizontalView: 'carbon:horizontal-view',
  ListBulleted: 'carbon:list-bulleted',
  ListChecked: 'carbon:list-checked',
  UserAvatar: 'carbon:user-avatar',
  Badge: 'carbon:badge',
  CalendarHeatMap: 'carbon:calendar-heat-map',
  CarouselHorizontal: 'carbon:carousel-horizontal',
  BorderVerticleOutlined: 'ant-design:border-verticle-outlined',
  BoxPlotOutlined: 'ant-design:box-plot-outlined',
  TreeViewAlt: 'carbon:tree-view-alt',
  Drought: 'carbon:drought',
  Help: 'carbon:help',
  Add: 'carbon:add',
  Close: 'carbon:close',
}

export function resolveModuleIcon(elIcon?: string): string {
  if (!elIcon) return 'carbon:cube'
  if (elIcon.includes(':')) return elIcon
  return ICON_MAP[elIcon] ?? `carbon:${elIcon.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase()}`
}
