import type { ReportChartType } from '../chartTypes'
import {
  advancedOptionFields,
  cartesianAxisFields,
  commonVisualFields,
  seriesEmphasisFields,
  seriesItemStyleFields,
  seriesLabelFields,
  seriesLineStyleFields,
  seriesMetaFields,
  symbolOptions,
  visualMapFields,
} from './commonFields'
import {
  boolSwitch,
  colorInput,
  numberInput,
  sectionTitle,
  selectInput,
  textInput,
  type ChartPropConfigItem,
} from './propHelpers'

const withCommon = (...groups: ChartPropConfigItem[][]): ChartPropConfigItem[] => [
  ...commonVisualFields(),
  ...groups.flat(),
  ...advancedOptionFields(),
]

const cartesianFields = (): ChartPropConfigItem[] =>
  withCommon(cartesianAxisFields(), [
    sectionTitle('双 Y 轴'),
    boolSwitch('显示右轴', 'yAxisRight.show'),
    textInput('右轴名称', 'yAxisRight.name'),
    selectInput('右轴类型', 'yAxisRight.type', [
      { label: '数值', value: 'value' },
      { label: '类目', value: 'category' },
      { label: '时间', value: 'time' },
      { label: '对数', value: 'log' },
    ]),
    boolSwitch('右轴脱离 0 值', 'yAxisRight.scale'),
    textInput('右轴最小值', 'yAxisRight.min'),
    textInput('右轴最大值', 'yAxisRight.max'),
    boolSwitch('右轴反向', 'yAxisRight.inverse'),
    sectionTitle('系列'),
    {
      eleType: 'ChartSeriesListEditor',
      name: '系列列表',
      describe: '对齐 ECharts series（line/bar/scatter/candlestick）视觉配置，可拖拽排序；允许为空',
      modelKey: 'seriesList',
    },
  ])

const boxplotFields = (): ChartPropConfigItem[] =>
  withCommon(cartesianAxisFields(), [
    ...seriesMetaFields(),
    sectionTitle('盒须系列'),
    textInput('盒宽', 'seriesStyle.boxWidth', '可为数组，如 [7,50]'),
    selectInput('布局', 'seriesStyle.layout', [
      { label: '默认竖向', value: '' },
      { label: 'horizontal', value: 'horizontal' },
    ]),
    boolSwitch('悬停动画', 'seriesStyle.hoverAnimation'),
    colorInput('盒体色', 'seriesStyle.itemStyle.color'),
    colorInput('盒体边框', 'seriesStyle.itemStyle.borderColor'),
    numberInput('盒体边框宽', 'seriesStyle.itemStyle.borderWidth'),
    numberInput('透明度', 'seriesStyle.itemStyle.opacity'),
    ...seriesEmphasisFields(),
    ...seriesLabelFields(),
  ])

const heatmapFields = (): ChartPropConfigItem[] =>
  withCommon(cartesianAxisFields(), visualMapFields(), [
    ...seriesMetaFields(),
    sectionTitle('热力系列'),
    numberInput('模糊大小', 'seriesStyle.blurSize'),
    numberInput('点大小', 'seriesStyle.pointSize'),
    numberInput('最大透明度', 'seriesStyle.maxOpacity'),
    numberInput('最小透明度', 'seriesStyle.minOpacity'),
    boolSwitch('渐进式渲染', 'seriesStyle.progressive'),
    numberInput('渐进阈值', 'seriesStyle.progressiveThreshold'),
    ...seriesItemStyleFields(),
    ...seriesEmphasisFields(),
    ...seriesLabelFields(),
  ])

const radarFields = (): ChartPropConfigItem[] =>
  withCommon([
    sectionTitle('雷达坐标系'),
    selectInput('形状', 'radar.shape', [
      { label: '多边形', value: 'polygon' },
      { label: '圆形', value: 'circle' },
    ]),
    numberInput('分割段数', 'radar.splitNumber'),
    textInput('半径', 'radar.radius', '如 65% 或 120'),
    textInput('中心', 'radar.center', '如 ["50%","50%"]'),
    numberInput('起始角度', 'radar.startAngle'),
    numberInput('名称间距', 'radar.nameGap'),
    boolSwitch('刻度朝内', 'radar.axisTick.inside'),
    boolSwitch('显示刻度', 'radar.axisTick.show'),
    boolSwitch('显示刻度标签', 'radar.axisLabel.show'),
    colorInput('刻度标签色', 'radar.axisLabel.color'),
    numberInput('刻度标签字号', 'radar.axisLabel.fontSize'),
    numberInput('z', 'radar.z'),
    numberInput('zlevel', 'radar.zlevel'),
    {
      eleType: 'ChartRadarIndicatorListEditor',
      name: '指示器 indicator',
      describe: '对应 ECharts radar.indicator，可逐项配置名称与最大值',
      modelKey: 'radar.indicator',
    },
    sectionTitle('指示器名称样式'),
    boolSwitch('显示指示器名', 'radar.axisName.show'),
    selectInput('名称格式', 'radar.axisName.nameFormat', [
      { label: '原样', value: 'none' },
      { label: '自定义', value: 'custom' },
    ]),
    textInput(
      '自定义格式',
      'radar.axisName.formatter',
      '名称格式=自定义时生效，可用 {value}',
      '【{value}】',
    ),
    colorInput('名称颜色', 'radar.axisName.color'),
    colorInput('名称背景', 'radar.axisName.backgroundColor'),
    numberInput('名称圆角', 'radar.axisName.borderRadius'),
    textInput('名称内边距', 'radar.axisName.padding', '如 3 或 3,5；留空则不设置'),
    sectionTitle('分割区 / 圆环'),
    boolSwitch('显示分割区', 'radar.splitArea.show'),
    {
      eleType: 'ChartColorListEditor',
      name: '分割区填充色',
      describe: '同心环面填充色，由外到内；可添加、删除并拖拽排序',
      modelKey: 'radar.splitAreaColors',
    },
    colorInput('分割区阴影色', 'radar.splitArea.areaStyle.shadowColor'),
    numberInput('分割区阴影模糊', 'radar.splitArea.areaStyle.shadowBlur'),
    boolSwitch('显示圆环轮廓', 'radar.splitLine.show'),
    {
      eleType: 'ChartColorListEditor',
      name: '圆环轮廓线',
      describe: '同心圆/多边形描边色，由外到内；可添加、删除并拖拽排序',
      modelKey: 'radar.splitLineColors',
    },
    numberInput('轮廓线宽', 'radar.splitLine.lineStyle.width'),
    selectInput('轮廓线型', 'radar.splitLine.lineStyle.type', [
      { label: '实线', value: 'solid' },
      { label: '虚线', value: 'dashed' },
      { label: '点线', value: 'dotted' },
    ]),
    colorInput('轴线颜色', 'radar.axisLine.lineStyle.color'),
    numberInput('轴线宽', 'radar.axisLine.lineStyle.width'),
    boolSwitch('显示轴线', 'radar.axisLine.show'),
    sectionTitle('雷达系列'),
    {
      eleType: 'ChartRadarSeriesListEditor',
      name: '系列列表',
      describe: '可配置面积填充、虚线、标记、数值标签；径向渐变用起止色',
      modelKey: 'radarSeriesList',
    },
  ])

const mapFields = (): ChartPropConfigItem[] =>
  withCommon(visualMapFields(), [
    ...seriesMetaFields(),
    sectionTitle('地图系列'),
    textInput('地图名称', 'seriesStyle.map', '内置 china，也可填已 registerMap 的名称'),
    selectInput('漫游', 'seriesStyle.roam', [
      { label: '关闭', value: false },
      { label: '开启', value: true },
      { label: '仅缩放', value: 'scale' },
      { label: '仅平移', value: 'move' },
    ]),
    textInput('中心', 'seriesStyle.center', '经纬度 [lng,lat]'),
    numberInput('缩放', 'seriesStyle.zoom'),
    numberInput('长宽比', 'seriesStyle.aspectScale'),
    textInput('布局中心', 'seriesStyle.layoutCenter', '如 ["50%","50%"]'),
    textInput('布局尺寸', 'seriesStyle.layoutSize', '如 80%'),
    boolSwitch('显示标签', 'seriesStyle.label.show'),
    colorInput('标签色', 'seriesStyle.label.color'),
    numberInput('标签字号', 'seriesStyle.label.fontSize'),
    colorInput('区域色', 'seriesStyle.itemStyle.areaColor'),
    colorInput('描边色', 'seriesStyle.itemStyle.borderColor'),
    numberInput('描边宽', 'seriesStyle.itemStyle.borderWidth'),
    numberInput('透明度', 'seriesStyle.itemStyle.opacity'),
    colorInput('高亮区域色', 'seriesStyle.emphasis.itemStyle.areaColor'),
    colorInput('高亮描边', 'seriesStyle.emphasis.itemStyle.borderColor'),
    boolSwitch('高亮显示标签', 'seriesStyle.emphasis.label.show'),
    sectionTitle('Geo 组件'),
    boolSwitch('显示 Geo', 'geo.show'),
    textInput('Geo 地图名', 'geo.map'),
    selectInput('Geo 漫游', 'geo.roam', [
      { label: '关闭', value: false },
      { label: '开启', value: true },
      { label: '仅缩放', value: 'scale' },
      { label: '仅平移', value: 'move' },
    ]),
    numberInput('Geo 缩放', 'geo.zoom'),
    textInput('Geo 中心', 'geo.center'),
    textInput('Geo 布局中心', 'geo.layoutCenter'),
    textInput('Geo 布局尺寸', 'geo.layoutSize'),
    boolSwitch('Geo 标签', 'geo.label.show'),
    colorInput('Geo 区域色', 'geo.itemStyle.areaColor'),
    colorInput('Geo 描边色', 'geo.itemStyle.borderColor'),
    numberInput('Geo 描边宽', 'geo.itemStyle.borderWidth'),
  ])

const graphFields = (): ChartPropConfigItem[] =>
  withCommon([
    ...seriesMetaFields(),
    sectionTitle('关系图'),
    selectInput('布局', 'seriesStyle.layout', [
      { label: '力引导', value: 'force' },
      { label: '环形', value: 'circular' },
      { label: '无（使用 x/y）', value: 'none' },
    ]),
    selectInput('漫游', 'seriesStyle.roam', [
      { label: '关闭', value: false },
      { label: '开启', value: true },
      { label: '仅缩放', value: 'scale' },
      { label: '仅平移', value: 'move' },
    ]),
    boolSwitch('可拖拽节点', 'seriesStyle.draggable'),
    boolSwitch('鼠标漫游聚焦邻接', 'seriesStyle.focusNodeAdjacency'),
    selectInput('标记', 'seriesStyle.symbol', symbolOptions),
    numberInput('标记大小', 'seriesStyle.symbolSize'),
    numberInput('最小缩放', 'seriesStyle.scaleLimit.min'),
    numberInput('最大缩放', 'seriesStyle.scaleLimit.max'),
    sectionTitle('力引导 force'),
    numberInput('斥力', 'seriesStyle.force.repulsion'),
    numberInput('边长', 'seriesStyle.force.edgeLength'),
    numberInput('向心力', 'seriesStyle.force.gravity'),
    numberInput('摩擦', 'seriesStyle.force.friction'),
    boolSwitch('布局动画', 'seriesStyle.force.layoutAnimation'),
    sectionTitle('环形 circular'),
    boolSwitch('标签旋转', 'seriesStyle.circular.rotateLabel'),
    ...seriesLabelFields(),
    ...seriesItemStyleFields(),
    ...seriesLineStyleFields(),
    ...seriesEmphasisFields(),
    sectionTitle('边标签 edgeLabel'),
    boolSwitch('显示边标签', 'seriesStyle.edgeLabel.show'),
    colorInput('边标签色', 'seriesStyle.edgeLabel.color'),
    numberInput('边标签字号', 'seriesStyle.edgeLabel.fontSize'),
  ])

const treeFields = (): ChartPropConfigItem[] =>
  withCommon([
    ...seriesMetaFields(),
    sectionTitle('树图'),
    selectInput('布局', 'seriesStyle.layout', [
      { label: '正交', value: 'orthogonal' },
      { label: '径向', value: 'radial' },
    ]),
    selectInput('方向', 'seriesStyle.orient', [
      { label: '从左到右', value: 'LR' },
      { label: '从右到左', value: 'RL' },
      { label: '从上到下', value: 'TB' },
      { label: '从下到上', value: 'BT' },
    ]),
    selectInput('漫游', 'seriesStyle.roam', [
      { label: '关闭', value: false },
      { label: '开启', value: true },
      { label: '仅缩放', value: 'scale' },
      { label: '仅平移', value: 'move' },
    ]),
    selectInput('边形状', 'seriesStyle.edgeShape', [
      { label: '曲线', value: 'curve' },
      { label: '折线', value: 'polyline' },
    ]),
    textInput('分叉位置', 'seriesStyle.edgeForkPosition', '如 50%'),
    selectInput('标记', 'seriesStyle.symbol', symbolOptions),
    numberInput('标记大小', 'seriesStyle.symbolSize'),
    boolSwitch('展开收起', 'seriesStyle.expandAndCollapse'),
    numberInput('初始展开深度', 'seriesStyle.initialTreeDepth'),
    textInput('左边距', 'seriesStyle.left'),
    textInput('上边距', 'seriesStyle.top'),
    textInput('右边距', 'seriesStyle.right'),
    textInput('下边距', 'seriesStyle.bottom'),
    textInput('宽度', 'seriesStyle.width'),
    textInput('高度', 'seriesStyle.height'),
    ...seriesLabelFields(),
    ...seriesItemStyleFields(),
    ...seriesLineStyleFields(),
    ...seriesEmphasisFields(),
    sectionTitle('叶子标签 leaves.label'),
    boolSwitch('显示叶子标签', 'seriesStyle.leaves.label.show'),
    selectInput('叶子标签位置', 'seriesStyle.leaves.label.position', [
      { label: 'left', value: 'left' },
      { label: 'right', value: 'right' },
      { label: 'top', value: 'top' },
      { label: 'bottom', value: 'bottom' },
    ]),
  ])

const treemapFields = (): ChartPropConfigItem[] =>
  withCommon([
    ...seriesMetaFields(),
    sectionTitle('矩形树图'),
    selectInput('漫游', 'seriesStyle.roam', [
      { label: '关闭', value: false },
      { label: '开启', value: true },
      { label: '仅缩放', value: 'scale' },
      { label: '仅平移', value: 'move' },
    ]),
    selectInput('节点点击', 'seriesStyle.nodeClick', [
      { label: '缩放到节点', value: 'zoomToNode' },
      { label: '链接跳转', value: 'link' },
      { label: '关闭', value: false },
    ]),
    numberInput('缩放比 zoomToNodeRatio', 'seriesStyle.zoomToNodeRatio'),
    numberInput('方块比例 squareRatio', 'seriesStyle.squareRatio'),
    numberInput('叶子深度 leafDepth', 'seriesStyle.leafDepth'),
    textInput('left', 'seriesStyle.left'),
    textInput('top', 'seriesStyle.top'),
    textInput('right', 'seriesStyle.right'),
    textInput('bottom', 'seriesStyle.bottom'),
    textInput('width', 'seriesStyle.width'),
    textInput('height', 'seriesStyle.height'),
    sectionTitle('面包屑'),
    boolSwitch('显示面包屑', 'seriesStyle.breadcrumb.show'),
    textInput('面包屑 left', 'seriesStyle.breadcrumb.left'),
    textInput('面包屑 top', 'seriesStyle.breadcrumb.top'),
    textInput('面包屑 right', 'seriesStyle.breadcrumb.right'),
    textInput('面包屑 bottom', 'seriesStyle.breadcrumb.bottom'),
    colorInput('面包屑文字色', 'seriesStyle.breadcrumb.itemStyle.textStyle.color'),
    ...seriesLabelFields(),
    ...seriesItemStyleFields(),
    ...seriesEmphasisFields(),
  ])

const sunburstFields = (): ChartPropConfigItem[] =>
  withCommon([
    ...seriesMetaFields(),
    sectionTitle('旭日图'),
    textInput('半径', 'seriesStyle.radius', '如 ["15%","80%"]'),
    textInput('中心', 'seriesStyle.center', '如 ["50%","50%"]'),
    numberInput('起始角度', 'seriesStyle.startAngle'),
    boolSwitch('顺时针', 'seriesStyle.clockwise'),
    selectInput('节点点击', 'seriesStyle.nodeClick', [
      { label: '根到节点', value: 'rootToNode' },
      { label: '链接', value: 'link' },
      { label: '关闭', value: false },
    ]),
    selectInput('排序', 'seriesStyle.sort', [
      { label: 'desc', value: 'desc' },
      { label: 'asc', value: 'asc' },
      { label: '关闭', value: null },
    ]),
    selectInput('高亮策略', 'seriesStyle.highlightPolicy', [
      { label: 'descendant', value: 'descendant' },
      { label: 'ancestor', value: 'ancestor' },
      { label: 'self', value: 'self' },
      { label: 'none', value: 'none' },
    ]),
    ...seriesLabelFields(),
    ...seriesItemStyleFields(),
    ...seriesEmphasisFields(),
  ])

const parallelFields = (): ChartPropConfigItem[] =>
  withCommon([
    ...seriesMetaFields(),
    sectionTitle('平行坐标系列'),
    numberInput('线宽', 'seriesStyle.lineStyle.width'),
    numberInput('透明度', 'seriesStyle.lineStyle.opacity'),
    colorInput('线颜色', 'seriesStyle.lineStyle.color'),
    selectInput('线型', 'seriesStyle.lineStyle.type', [
      { label: '实线', value: 'solid' },
      { label: '虚线', value: 'dashed' },
      { label: '点线', value: 'dotted' },
    ]),
    boolSwitch('平滑', 'seriesStyle.smooth'),
    numberInput('渐进阈值', 'seriesStyle.progressiveThreshold'),
    sectionTitle('平行轴默认'),
    selectInput('默认轴类型', 'parallelAxisDefault.type', [
      { label: '数值', value: 'value' },
      { label: '类目', value: 'category' },
    ]),
    selectInput('名称位置', 'parallelAxisDefault.nameLocation', [
      { label: 'start', value: 'start' },
      { label: 'middle', value: 'middle' },
      { label: 'end', value: 'end' },
    ]),
    numberInput('名称间距', 'parallelAxisDefault.nameGap'),
    boolSwitch('显示刻度标签', 'parallelAxisDefault.axisLabel.show'),
    colorInput('标签色', 'parallelAxisDefault.axisLabel.color'),
    boolSwitch('显示轴线', 'parallelAxisDefault.axisLine.show'),
    colorInput('轴线色', 'parallelAxisDefault.axisLine.lineStyle.color'),
    ...seriesEmphasisFields(),
  ])

const sankeyFields = (): ChartPropConfigItem[] =>
  withCommon([
    ...seriesMetaFields(),
    sectionTitle('桑基图'),
    selectInput('方向', 'seriesStyle.orient', [
      { label: '水平', value: 'horizontal' },
      { label: '垂直', value: 'vertical' },
    ]),
    selectInput('节点对齐', 'seriesStyle.nodeAlign', [
      { label: '两端对齐', value: 'justify' },
      { label: '左', value: 'left' },
      { label: '右', value: 'right' },
    ]),
    numberInput('布局迭代次数', 'seriesStyle.layoutIterations'),
    numberInput('节点宽度', 'seriesStyle.nodeWidth'),
    numberInput('节点间距', 'seriesStyle.nodeGap'),
    boolSwitch('可拖拽', 'seriesStyle.draggable'),
    textInput('left', 'seriesStyle.left'),
    textInput('top', 'seriesStyle.top'),
    textInput('right', 'seriesStyle.right'),
    textInput('bottom', 'seriesStyle.bottom'),
    textInput('width', 'seriesStyle.width'),
    textInput('height', 'seriesStyle.height'),
    ...seriesLabelFields(),
    ...seriesItemStyleFields(),
    ...seriesLineStyleFields(),
    ...seriesEmphasisFields(),
  ])

const funnelFields = (): ChartPropConfigItem[] =>
  withCommon([
    ...seriesMetaFields(),
    sectionTitle('漏斗图'),
    selectInput('排序', 'seriesStyle.sort', [
      { label: '降序', value: 'descending' },
      { label: '升序', value: 'ascending' },
      { label: '无', value: 'none' },
    ]),
    selectInput('朝向', 'seriesStyle.orient', [
      { label: '垂直', value: 'vertical' },
      { label: '水平', value: 'horizontal' },
    ]),
    selectInput('漏斗对齐', 'seriesStyle.funnelAlign', [
      { label: '居中', value: 'center' },
      { label: '左', value: 'left' },
      { label: '右', value: 'right' },
    ]),
    numberInput('间距', 'seriesStyle.gap'),
    numberInput('最小值', 'seriesStyle.min'),
    numberInput('最大值', 'seriesStyle.max'),
    textInput('最小尺寸', 'seriesStyle.minSize'),
    textInput('最大尺寸', 'seriesStyle.maxSize'),
    textInput('left', 'seriesStyle.left'),
    textInput('top', 'seriesStyle.top'),
    textInput('right', 'seriesStyle.right'),
    textInput('bottom', 'seriesStyle.bottom'),
    textInput('width', 'seriesStyle.width'),
    textInput('height', 'seriesStyle.height'),
    ...seriesLabelFields(),
    sectionTitle('引导线 labelLine'),
    boolSwitch('显示引导线', 'seriesStyle.labelLine.show'),
    numberInput('引导线长', 'seriesStyle.labelLine.length'),
    colorInput('引导线色', 'seriesStyle.labelLine.lineStyle.color'),
    numberInput('引导线宽', 'seriesStyle.labelLine.lineStyle.width'),
    ...seriesItemStyleFields(),
    ...seriesEmphasisFields(),
  ])

const gaugeFields = (): ChartPropConfigItem[] =>
  withCommon([
    ...seriesMetaFields(),
    sectionTitle('仪表盘'),
    textInput('中心', 'seriesStyle.center', '如 ["50%","50%"]'),
    textInput('半径', 'seriesStyle.radius', '如 75%'),
    numberInput('最小值', 'seriesStyle.min'),
    numberInput('最大值', 'seriesStyle.max'),
    numberInput('分割段数', 'seriesStyle.splitNumber'),
    numberInput('起始角度', 'seriesStyle.startAngle'),
    numberInput('结束角度', 'seriesStyle.endAngle'),
    boolSwitch('顺时针', 'seriesStyle.clockwise'),
    sectionTitle('进度条 progress'),
    boolSwitch('显示进度条', 'seriesStyle.progress.show'),
    boolSwitch('重叠', 'seriesStyle.progress.overlap'),
    boolSwitch('裁剪宽度', 'seriesStyle.progress.clip'),
    numberInput('进度宽度', 'seriesStyle.progress.width'),
    boolSwitch('圆角端点', 'seriesStyle.progress.roundCap'),
    colorInput('进度色', 'seriesStyle.progress.itemStyle.color'),
    sectionTitle('详情 detail'),
    boolSwitch('显示详情值', 'seriesStyle.detail.show'),
    textInput('详情 formatter', 'seriesStyle.detail.formatter', '如 {value}%'),
    numberInput('详情字号', 'seriesStyle.detail.fontSize'),
    colorInput('详情颜色', 'seriesStyle.detail.color'),
    numberInput('详情字重', 'seriesStyle.detail.fontWeight'),
    textInput('详情偏移', 'seriesStyle.detail.offsetCenter', '如 [0,"40%"]'),
    sectionTitle('指针 pointer'),
    boolSwitch('显示指针', 'seriesStyle.pointer.show'),
    textInput('指针长度', 'seriesStyle.pointer.length'),
    numberInput('指针宽度', 'seriesStyle.pointer.width'),
    colorInput('指针色', 'seriesStyle.pointer.itemStyle.color'),
    sectionTitle('锚点 anchor'),
    boolSwitch('显示锚点', 'seriesStyle.anchor.show'),
    boolSwitch('锚点在上方', 'seriesStyle.anchor.showAbove'),
    numberInput('锚点大小', 'seriesStyle.anchor.size'),
    colorInput('锚点色', 'seriesStyle.anchor.itemStyle.color'),
    sectionTitle('轴线 axisLine'),
    boolSwitch('显示轴线', 'seriesStyle.axisLine.show'),
    numberInput('轴线宽', 'seriesStyle.axisLine.lineStyle.width'),
    textInput('轴线色段', 'seriesStyle.axisLine.lineStyle.color', '如 [[0.3,"#67e"],[1,"#e66"]]'),
    sectionTitle('刻度 axisTick / splitLine'),
    boolSwitch('显示刻度', 'seriesStyle.axisTick.show'),
    numberInput('刻度长度', 'seriesStyle.axisTick.length'),
    numberInput('刻度分割', 'seriesStyle.axisTick.splitNumber'),
    colorInput('刻度色', 'seriesStyle.axisTick.lineStyle.color'),
    boolSwitch('显示分隔线', 'seriesStyle.splitLine.show'),
    numberInput('分隔线长', 'seriesStyle.splitLine.length'),
    colorInput('分隔线色', 'seriesStyle.splitLine.lineStyle.color'),
    sectionTitle('刻度标签'),
    boolSwitch('显示刻度标签', 'seriesStyle.axisLabel.show'),
    numberInput('标签距离', 'seriesStyle.axisLabel.distance'),
    colorInput('标签色', 'seriesStyle.axisLabel.color'),
    numberInput('标签字号', 'seriesStyle.axisLabel.fontSize'),
    textInput('标签 formatter', 'seriesStyle.axisLabel.formatter'),
    sectionTitle('标题 title'),
    boolSwitch('显示系列标题', 'seriesStyle.title.show'),
    textInput('标题偏移', 'seriesStyle.title.offsetCenter'),
    colorInput('标题色', 'seriesStyle.title.color'),
    numberInput('标题字号', 'seriesStyle.title.fontSize'),
    ...seriesEmphasisFields(),
  ])

const themeRiverFields = (): ChartPropConfigItem[] =>
  withCommon([
    ...seriesMetaFields(),
    sectionTitle('主题河流'),
    textInput('left', 'seriesStyle.left'),
    textInput('top', 'seriesStyle.top'),
    textInput('right', 'seriesStyle.right'),
    textInput('bottom', 'seriesStyle.bottom'),
    textInput('width', 'seriesStyle.width'),
    textInput('height', 'seriesStyle.height'),
    ...seriesLabelFields(),
    ...seriesItemStyleFields(),
    ...seriesEmphasisFields(),
  ])

const calendarFields = (): ChartPropConfigItem[] =>
  withCommon(visualMapFields(), [
    sectionTitle('日历坐标'),
    selectInput('方向', 'calendar.orient', [
      { label: '水平', value: 'horizontal' },
      { label: '垂直', value: 'vertical' },
    ]),
    textInput('范围 range', 'calendar.range', '如 2024 或 ["2024-01","2024-12"]'),
    textInput('水平位置', 'calendar.left'),
    textInput('垂直位置', 'calendar.top'),
    textInput('右边距', 'calendar.right'),
    textInput('下边距', 'calendar.bottom'),
    textInput('单元格大小', 'calendar.cellSize', '数值或 [宽,高]'),
    numberInput('z', 'calendar.z'),
    numberInput('zlevel', 'calendar.zlevel'),
    sectionTitle('年 / 月 / 日标签'),
    boolSwitch('显示年标签', 'calendar.yearLabel.show'),
    colorInput('年标签色', 'calendar.yearLabel.color'),
    numberInput('年标签字号', 'calendar.yearLabel.fontSize'),
    textInput('年标签 formatter', 'calendar.yearLabel.formatter'),
    boolSwitch('显示月标签', 'calendar.monthLabel.show'),
    colorInput('月标签色', 'calendar.monthLabel.color'),
    numberInput('月标签字号', 'calendar.monthLabel.fontSize'),
    selectInput('月标签位置', 'calendar.monthLabel.position', [
      { label: 'start', value: 'start' },
      { label: 'end', value: 'end' },
    ]),
    boolSwitch('显示日标签', 'calendar.dayLabel.show'),
    colorInput('日标签色', 'calendar.dayLabel.color'),
    numberInput('日标签字号', 'calendar.dayLabel.fontSize'),
    selectInput('周起始', 'calendar.dayLabel.firstDay', [
      { label: '周日', value: 0 },
      { label: '周一', value: 1 },
    ]),
    sectionTitle('日历项样式'),
    colorInput('项边框色', 'calendar.itemStyle.borderColor'),
    numberInput('项边框宽', 'calendar.itemStyle.borderWidth'),
    colorInput('项颜色', 'calendar.itemStyle.color'),
    ...seriesMetaFields(),
    ...seriesItemStyleFields(),
    ...seriesLabelFields(),
    ...seriesEmphasisFields(),
  ])

const matrixFields = (): ChartPropConfigItem[] =>
  withCommon(cartesianAxisFields(), visualMapFields(), [
    ...seriesMetaFields(),
    sectionTitle('矩阵（热力）'),
    numberInput('模糊大小', 'seriesStyle.blurSize'),
    numberInput('点大小', 'seriesStyle.pointSize'),
    ...seriesItemStyleFields(),
    ...seriesEmphasisFields(),
    ...seriesLabelFields(),
  ])

const chordFields = (): ChartPropConfigItem[] =>
  withCommon([
    ...seriesMetaFields(),
    sectionTitle('和弦图（graph 环形）'),
    selectInput('布局', 'seriesStyle.layout', [
      { label: '环形', value: 'circular' },
      { label: '力引导', value: 'force' },
      { label: '无', value: 'none' },
    ]),
    boolSwitch('标签旋转', 'seriesStyle.circular.rotateLabel'),
    selectInput('漫游', 'seriesStyle.roam', [
      { label: '关闭', value: false },
      { label: '开启', value: true },
      { label: '仅缩放', value: 'scale' },
      { label: '仅平移', value: 'move' },
    ]),
    selectInput('标记', 'seriesStyle.symbol', symbolOptions),
    numberInput('标记大小', 'seriesStyle.symbolSize'),
    ...seriesLabelFields(),
    ...seriesItemStyleFields(),
    ...seriesLineStyleFields(),
    ...seriesEmphasisFields(),
    sectionTitle('边标签'),
    boolSwitch('显示边标签', 'seriesStyle.edgeLabel.show'),
    colorInput('边标签色', 'seriesStyle.edgeLabel.color'),
    numberInput('边标签字号', 'seriesStyle.edgeLabel.fontSize'),
  ])

/** chartType → 配置字段列表 */
export const chartOptionFieldsMap: Record<ReportChartType, () => ChartPropConfigItem[]> = {
  cartesian: cartesianFields,
  map: mapFields,
  radar: radarFields,
  boxplot: boxplotFields,
  heatmap: heatmapFields,
  graph: graphFields,
  tree: treeFields,
  treemap: treemapFields,
  sunburst: sunburstFields,
  parallel: parallelFields,
  sankey: sankeyFields,
  funnel: funnelFields,
  gauge: gaugeFields,
  themeRiver: themeRiverFields,
  calendar: calendarFields,
  matrix: matrixFields,
  chord: chordFields,
}

export function getChartOptionFields(chartType: ReportChartType): ChartPropConfigItem[] {
  return (chartOptionFieldsMap[chartType] || cartesianFields)()
}
