import { MenuTypeEnum } from '@grow-admin-rock/constants'
import type { DesignerMenuApiItem } from './config'

export const DESIGNER_MENU_LIST: DesignerMenuApiItem[] = [
  {
    name: 'DesignerCatalog',
    title: '自动化',
    icon: 'ant-design:appstore-outlined',
    menuType: MenuTypeEnum.DIRECTORY,
    isVisible: true,
    sort: 36,
    children: [
      {
        name: 'OnlinePageManage',
        title: '在线页面管理',
        icon: 'ant-design:code-sandbox-outlined',
        menuType: MenuTypeEnum.MENU,
        isVisible: true,
        isKeepAlive: true,
        sort: 1,
        children: [
          {
            name: 'OnlinePageDesign',
            title: '在线页面设计',
            icon: 'ant-design:code-sandbox-outlined',
            menuType: MenuTypeEnum.MENU,
            isVisible: false,
            isKeepAlive: true,
            sort: 10,
          },
        ],
      },
      {
        name: 'LowcodeAssetManage',
        title: '低代码资产管理',
        icon: 'ant-design:file-protect-outlined',
        menuType: MenuTypeEnum.MENU,
        isVisible: true,
        isKeepAlive: true,
        sort: 5,
        children: [
          {
            name: 'LowcodeAssetDesign',
            title: '低代码设计',
            icon: 'ant-design:build-outlined',
            menuType: MenuTypeEnum.MENU,
            isVisible: false,
            isKeepAlive: true,
            sort: 10,
          },
        ],
      },
      {
        name: 'ReportAssetManage',
        title: '报表资产管理',
        icon: 'ant-design:bar-chart-outlined',
        menuType: MenuTypeEnum.MENU,
        isVisible: true,
        isKeepAlive: true,
        sort: 20,
        children: [
          {
            name: 'ReportAssetDesign',
            title: '报表设计',
            icon: 'ant-design:bar-chart-outlined',
            menuType: MenuTypeEnum.MENU,
            isVisible: false,
            isKeepAlive: true,
            sort: 10,
          },
        ],
      },
      {
        name: 'SchemaAssetManage',
        title: '数据库建模管理',
        icon: 'ant-design:database-outlined',
        menuType: MenuTypeEnum.MENU,
        isVisible: true,
        isKeepAlive: true,
        sort: 30,
        children: [
          {
            name: 'SchemaAssetDesign',
            title: '数据库建模设计',
            icon: 'ant-design:database-outlined',
            menuType: MenuTypeEnum.MENU,
            isVisible: false,
            isKeepAlive: true,
            sort: 10,
          },
        ],
      },
      {
        name: 'DataPrepAssetManage',
        title: '数据准备管理',
        icon: 'ant-design:partition-outlined',
        menuType: MenuTypeEnum.MENU,
        isVisible: true,
        isKeepAlive: true,
        sort: 40,
        children: [
          {
            name: 'DataPrepAssetDesign',
            title: '数据准备设计',
            icon: 'ant-design:partition-outlined',
            menuType: MenuTypeEnum.MENU,
            isVisible: false,
            isKeepAlive: true,
            sort: 10,
          },
        ],
      },
      {
        name: 'DataCleanAssetManage',
        title: '数据清洗管理',
        icon: 'ant-design:clear-outlined',
        menuType: MenuTypeEnum.MENU,
        isVisible: true,
        isKeepAlive: true,
        sort: 50,
        children: [
          {
            name: 'DataCleanAssetDesign',
            title: '数据清洗设计',
            icon: 'ant-design:clear-outlined',
            menuType: MenuTypeEnum.MENU,
            isVisible: false,
            isKeepAlive: true,
            sort: 10,
          },
        ],
      },
      {
        name: 'ProcessAssetManage',
        title: '流程引擎管理',
        icon: 'ant-design:apartment-outlined',
        menuType: MenuTypeEnum.MENU,
        isVisible: true,
        isKeepAlive: true,
        sort: 60,
        children: [
          {
            name: 'ProcessAssetDesign',
            title: '流程引擎设计',
            icon: 'ant-design:apartment-outlined',
            menuType: MenuTypeEnum.MENU,
            isVisible: false,
            isKeepAlive: true,
            sort: 10,
          },
        ],
      },
    ],
  },
]
