import { MenuTypeEnum } from '@grow-admin-rock/constants'
import type { SystemMenuApiItem } from './config'

export const SYSTEM_MENU_LIST: SystemMenuApiItem[] = [
  {
    name: 'SystemCatalog',
    title: '系统管理',
    icon: 'ant-design:setting-outlined',
    menuType: MenuTypeEnum.DIRECTORY,
    isVisible: true,
    sort: 37,
    children: [
      {
        name: 'MenuManage',
        title: '菜单管理',
        icon: 'ant-design:menu-outlined',
        menuType: MenuTypeEnum.MENU,
        isVisible: true,
        isKeepAlive: true,
        sort: 10,
      },
      {
        name: 'RoleManage',
        title: '角色管理',
        icon: 'ant-design:team-outlined',
        menuType: MenuTypeEnum.MENU,
        isVisible: true,
        isKeepAlive: true,
        sort: 20,
      },
      {
        name: 'AccountManage',
        title: '账号管理',
        icon: 'ant-design:lock-outlined',
        menuType: MenuTypeEnum.MENU,
        isVisible: true,
        isKeepAlive: true,
        sort: 25,
      },
      {
        name: 'PersonManage',
        title: '人员管理',
        icon: 'ant-design:user-outlined',
        menuType: MenuTypeEnum.MENU,
        isVisible: true,
        isKeepAlive: true,
        sort: 30,
        children: [
          {
            name: 'PersonCreate',
            title: '新增人员',
            icon: 'ant-design:user-add-outlined',
            menuType: MenuTypeEnum.MENU,
            isVisible: false,
            isKeepAlive: true,
            sort: 10,
          },
          {
            name: 'PersonDetail',
            title: '人员详情',
            icon: 'ant-design:profile-outlined',
            menuType: MenuTypeEnum.MENU,
            isVisible: false,
            isKeepAlive: true,
            sort: 20,
          },
        ],
      },
      {
        name: 'DeptManage',
        title: '部门管理',
        icon: 'ant-design:apartment-outlined',
        menuType: MenuTypeEnum.MENU,
        isVisible: true,
        isKeepAlive: true,
        sort: 35,
      },
      {
        name: 'PostManage',
        title: '岗位管理',
        icon: 'ant-design:idcard-outlined',
        menuType: MenuTypeEnum.MENU,
        isVisible: true,
        isKeepAlive: true,
        sort: 36,
      },
      {
        name: 'PositionManage',
        title: '职级管理',
        icon: 'ant-design:solution-outlined',
        menuType: MenuTypeEnum.MENU,
        isVisible: true,
        isKeepAlive: true,
        sort: 37,
      },
      {
        name: 'OrgChart',
        title: '组织架构图',
        icon: 'ant-design:cluster-outlined',
        menuType: MenuTypeEnum.MENU,
        isVisible: true,
        isKeepAlive: true,
        sort: 38,
      },
    ],
  },
]
